=== LayeNdiay/SocialeLite/DAO/msg.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <xsd:element name="messagerie">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="contacts" type="contactsType"/>
                <xsd:element name="groupes" type="groupesType"/>
                <xsd:element name="discussions" type="discussionsType"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <xsd:complexType name="contactsType">
        <xsd:sequence>
            <xsd:element name="contact" maxOccurs="unbounded">
                <xsd:complexType>
                    <xsd:sequence>
                        <xsd:element name="nom" type="xsd:string"/>
                        <xsd:element name="telephone" type="xsd:string"/>
                    </xsd:sequence>
                    <xsd:attribute name="id" type="xsd:string"/>
                </xsd:complexType>
            </xsd:element>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="groupesType">
        <xsd:sequence>
            <xsd:element name="groupe" maxOccurs="unbounded">
                <xsd:complexType>
                    <xsd:sequence>
                        <xsd:element name="nom" type="xsd:string"/>
                        <xsd:element name="membres" type="membresType"/>
                    </xsd:sequence>
                    <xsd:attribute name="id" type="xsd:string"  use="optional"/>
                </xsd:complexType>
            </xsd:element>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="membresType">
        <xsd:sequence>
            <xsd:element name="contact" minOccurs="0" maxOccurs="unbounded">
                <xsd:complexType>
                    <xsd:attribute name="id" type="xsd:string"/>
                </xsd:complexType>
            </xsd:element>
        </xsd:sequence>
    </xsd:complexType>
     <xsd:simpleType name="discType">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="individuel"></xsd:enumeration>
            <xsd:enumeration value="groupe"></xsd:enumeration>
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:complexType name="discussionsType">
        <xsd:sequence>
            <xsd:element name="discussion" maxOccurs="unbounded">
                <xsd:complexType>
                    <xsd:sequence>
                        <xsd:element name="participants" type="participantsType" minOccurs="0"/>
                        <xsd:element name="messages" type="messagesType"/>
                    </xsd:sequence>
                    <xsd:attribute name="id" type="xsd:string"/>
                    <xsd:attribute name="type" type="discType"/>
                    <xsd:attribute name="groupe" type="xsd:string" use="optional"/>

                </xsd:complexType>
            </xsd:element>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="participantsType">
        <xsd:sequence>
            <xsd:element name="participant" minOccurs="0" maxOccurs="unbounded">
                <xsd:complexType>
                    <xsd:attribute name="id" type="xsd:string"/>
                </xsd:complexType>
            </xsd:element>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="messagesType">
        <xsd:sequence>
            <xsd:element name="message" maxOccurs="unbounded">
                <xsd:complexType>
                    <xsd:sequence>
                        <xsd:element name="expediteur" type="expediteurType"/>
                        <xsd:element name="contenu" type="contenuType"/>
                        <xsd:element name="created_at" type="xsd:string"/>
                        <xsd:element name="citation" type="citationType" minOccurs="0"/>
                    </xsd:sequence>
                    <xsd:attribute name="id" type="xsd:string"/>
                </xsd:complexType>
            </xsd:element>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="expediteurType">
        <xsd:attribute name="id" type="xsd:string"/>
    </xsd:complexType>

<xsd:simpleType name="typeEnum">
    <xsd:restriction base="xsd:string">
        <xsd:enumeration value="texte"/>
        <xsd:enumeration value="photo"/>
        <xsd:enumeration value="audio"/>
        <xsd:enumeration value="fichier"/>
        <xsd:enumeration value="video"/>
        <xsd:enumeration value="vocal"/>
    </xsd:restriction>
</xsd:simpleType>

<xsd:complexType name="contenuType">
    <xsd:simpleContent>
        <xsd:extension base="xsd:string">
            <xsd:attribute name="type" type="typeEnum"/>
        </xsd:extension>
    </xsd:simpleContent>
</xsd:complexType>

    <xsd:complexType name="citationType">
        <xsd:attribute name="id" type="xsd:string"/>
    </xsd:complexType>
</xsd:schema>

=== LayeNdiay/SocialeLite/DAO/data.xml
<?xml version="1.0"?>
<!DOCTYPE messagerie>
<messagerie xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="msg.xsd">
    <contacts>
        <contact id="1">
            <nom>Mouhamed ba</nom>
            <telephone>777924666</telephone>
        </contact>
        <contact id="2">
            <nom>Mariame Sylla</nom>
            <telephone>+9876543210</telephone>
        </contact>
        <contact id="3">
            <nom>Laye Ndiay</nom>
            <telephone>+221772374233</telephone>
        </contact>
        <contact id="4">
            <nom>Assane</nom>
            <telephone>+9876543219</telephone>
        </contact>
        <contact id="5">
            <nom>admin</nom>
            <telephone>867647</telephone>
        </contact>
        <contact id="6">
            <nom>admin</nom>
            <telephone>000000000000000</telephone>
        </contact>
        <contact id="7">
            <nom>SENAP</nom>
            <telephone>92876544</telephone>
        </contact>
        <contact id="8">
            <nom>arouna keita</nom>
            <telephone>777923564</telephone>
        </contact>
        <contact id="9">
            <nom>My amigo</nom>
            <telephone>774320990</telephone>
        </contact>
        <contact id="10">
            <nom>pite</nom>
            <telephone>865475E54</telephone>
        </contact>
        <contact id="11">
            <nom>Astou Dia</nom>
            <telephone>778965432</telephone>
        </contact>
        <contact id="12">
            <nom>Oumar dia</nom>
            <telephone>3378465234</telephone>
        </contact>
        <contact id="13">
            <nom>ahmeth</nom>
            <telephone>786543667</telephone>
        </contact>
        <contact id="14">
            <nom>fallou </nom>
            <telephone>7786542345</telephone>
        </contact>
        <contact id="15">
            <nom>wade</nom>
            <telephone>778653478</telephone>
        </contact>
        <contact id="16">
            <nom>Mamadou</nom>
            <telephone>779002312</telephone>
        </contact>
        <contact id="17">
            <nom>lo</nom>
            <telephone>786542389</telephone>
        </contact>
    <contact id="18"><nom>astou</nom><telephone>7897653456</telephone></contact></contacts>
    <groupes>
        <groupe id="1">
            <nom>Amis proches</nom>
            <membres>
                <contact id="1"/>
                <contact id="2"/>
                <contact id="3"/>
                <contact id="4"/>
                <contact id="7"/>
            </membres>
        </groupe>
        <groupe id="2">
            <nom>Famille</nom>
            <membres>
                <contact id="1"/>
                <contact id="3"/>
            </membres>
        </groupe>
        <groupe id="3">
            <nom>Films</nom>
            <membres>
                <contact id="1"/>
            </membres>
        </groupe>

        <groupe id="4">
            <nom>Protocole</nom>
            <membres>
                <contact id="1"/>
                <contact id="1"/>
                <contact id="2"/>
            </membres>
        </groupe>
        <groupe id="5">
            <nom>DIC1</nom>
            <membres>
                <contact id="1"/>
                <contact id="1"/>
                <contact id="3"/>
                <contact id="2"/>
            </membres>
        </groupe>
    <groupe id="6"><nom>DIC TR</nom><membres><contact id="1"/><contact id="2"/></membres></groupe></groupes>
    <discussions>
        <discussion id="1" type="individuel">
            <participants>
                <participant id="1"/>
                <participant id="2"/>
            </participants>
            <messages>
                <message id="1">
                    <expediteur id="1"/>
                    <contenu type="texte">Salut Mariame, comment &#xE7;a va ?</contenu>
                    <created_at>2023-06-28 10:00:00</created_at>
                </message>
                <message id="3">
                    <expediteur id="2"/>
                    <contenu type="texte">&#xC7;a va bien, merci !</contenu>
                    <created_at>2023-06-28 10:02:00</created_at>
                    <citation id="1"/>
                </message>
                <message id="5">
                    <expediteur id="1"/>
                    <contenu type="texte">Tu as des nouvelles de Laye ?</contenu>
                    <created_at>2023-06-28 10:05:00</created_at>
                </message>
                <message id="7">
                    <expediteur id="2"/>
                    <contenu type="texte">Oui, il m'a dit qu'il allait bien.</contenu>
                    <created_at>2023-06-28 10:10:00</created_at>
                    <citation id="5"/>
                </message>
                <message id="1">
                    <expediteur id="1"/>
                    <contenu type="texte">bonsoir mariame</contenu>
                    <created_at>2023-07-07 20:10:16</created_at>
                </message>

                <message id="1">
                    <expediteur id="1"/>
                    <contenu type="texte">bonjour mariame</contenu>
                    <created_at>2023-07-13 17:34:43</created_at>
                    <citation id="7"/>
                </message>
                <message id="1">
                    <expediteur id="2"/>
                    <contenu type="texte">salut</contenu>
                    <created_at>2023-07-13 20:00:58</created_at>
                </message>
            <message id="7"><expediteur id="1"/><contenu type="texte">salut cv marie</contenu><created_at>2023-07-14 18:16:15</created_at><citation id="1"/></message></messages>
        </discussion>
        <discussion id="2" type="groupe" groupe="1">
            <messages>
                <message id="2">
                    <expediteur id="1"/>
                    <contenu type="audio">audio.mp3</contenu>
                    <created_at>2023-06-28 11:00:00</created_at>
                </message>
                <message id="4">
                    <expediteur id="3"/>
                    <contenu type="texte">Bonjour, j'ai une question.</contenu>
                    <created_at>2023-06-28 11:05:00</created_at>
                </message>
                <message id="6">
                    <expediteur id="4"/>
                    <contenu type="texte">Quelle est ta question ?</contenu>
                    <created_at>2023-06-28 11:10:00</created_at>
                    <citation id="4"/>
                </message>
                <message id="8">
                    <expediteur id="2"/>
                    <contenu type="texte">J'ai une id&#xE9;e, pourquoi ne pas organiser une sortie
                        ce
                        weekend ?</contenu>
                    <created_at>2023-06-28 11:15:00</created_at>
                </message>
            <message id="4"><expediteur id="1"/><contenu type="texte">salut tout le monde</contenu><created_at>2023-07-14 18:18:16</created_at><citation id="4"/></message></messages>
        </discussion>
        <discussion id="3" type="individuel">
            <participants>
                <participant id="1"/>
                <participant id="4"/>
            </participants>
            <messages>
                <message id="1">
                    <expediteur id="1"/>
                    <contenu type="texte">bonsoir cv ?</contenu>
                    <created_at>2023-07-14 01:07:20</created_at>
                </message>
            </messages>

        </discussion>
        <discussion id="2" type="groupe" groupe="3">
            <messages>
                <message id="2">
                    <expediteur id="1"/>
                    <contenu type="texte">Salut tout le monde !</contenu>
                    <created_at>2023-06-28 11:00:00</created_at>
                </message>
            </messages>
        </discussion>
        <discussion id="4" type="individuel">
            <participants>
                <participant id="1"/>
                <participant id="3"/>
            </participants>
            <messages>
                <message id="4">
                    <expediteur id="1"/>
                    <contenu type="texte">Salut Laye, comment vas-tu ?</contenu>
                    <created_at>2023-06-28 12:00:00</created_at>
                </message>
                <message id="5">
                    <expediteur id="3"/>
                    <contenu type="texte">Je vais bien, merci !</contenu>
                    <created_at>2023-06-28 12:02:00</created_at>
                    <citation id="4"/>
                </message>
                <message id="2">
                    <expediteur id="1"/>
                    <contenu type="texte">vous etes en vacs ?</contenu>
                    <created_at>2023-07-14 15:51:49</created_at>
                </message>
                <message id="3">
                    <expediteur id="3"/>
                    <contenu type="texte">oui en effet</contenu>
                    <created_at>2023-07-14 15:52:07</created_at>
                    <citation id="2"/>
                </message>
            </messages>
        </discussion>
        <discussion id="5" type="groupe" groupe="2">
            <messages>
                <message id="6">
                    <expediteur id="1"/>
                    <contenu type="texte">Salut Famille, comment allez-vous ?</contenu>
                    <created_at>2023-06-28 13:00:00</created_at>
                </message>
                <message id="7">
                    <expediteur id="3"/>
                    <contenu type="texte">Tout va bien de notre c&#xF4;t&#xE9; !</contenu>
                    <created_at>2023-06-28 13:02:00</created_at>
                    <citation id="6"/>
                </message>
            </messages>
        </discussion>
        <discussion id="6" type="individuel">
